name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_habits: yes
          plugin_achievements: yes
